
development:
  adapter: postgresql
  encoding: unicode
  database: pm_development
  pool: 5
  username: django
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pm_test
  pool: 5
  username: django
  password:
